"""
research/fmucd.py

External check on real maintenance work orders (analysis plan: research/AEI/analysis_plan_additions.md, section G).

Data: Facility Management Unified Classification Database (FMUCD), Mendeley Data
doi:10.17632/cb8d2nsjss.1 — 3,693,867 work orders from 12 North American universities with a
free-text `WODescription` and the organisation's own `WOPriority` code. The CSV (1.4 GB) is
downloaded to research/external/fmucd/fmucd.csv (gitignored, not redistributed).

Three steps, in order:

    inspect   priority-code profile per university, from label metadata only (no model runs),
              written to research/results/fmucd/priority_profile.md. Used to write the mapping
              from each university's codes to LOW / MEDIUM / HIGH by hand into
              research/external/fmucd_mapping.json, which is frozen before sampling.
    sample    unplanned work orders whose description is 3-200 characters and passes the
              production input guard, de-duplicated, seeded stratified sample across the three
              mapped bands and the universities -> research/results/fmucd/sample.csv.
    oracle    upper bound: classifiers trained on FMUCD's own labels (work orders disjoint from the
              sample) and tested on the sample, to show how much of the priority band is predictable
              from the text at all. Added after the agreement step came out near chance.
    score     agreement of every strategy with the mapped band: 3-class accuracy, quadratic
              weighted kappa, confusion, cluster bootstrap CIs and paired sign-flip tests.
              LLM outputs come from `collect.py --bank fmucd`; the non-LLM arms are computed here.

The recorded priority is scheduling policy as much as severity, so this is an agreement study,
not an accuracy test, and is reported as such.

Usage:
    python -m research.fmucd inspect
    python -m research.fmucd sample
    python -m research.fmucd score

Output:
    research/results/fmucd/{priority_profile.md,sample.csv,agreement.csv,summary.md}
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

CSV_PATH = PROJECT_ROOT / "research" / "external" / "fmucd" / "fmucd.csv"
MAPPING_PATH = PROJECT_ROOT / "research" / "external" / "fmucd_mapping.json"
OUT_DIR = PROJECT_ROOT / "research" / "results" / "fmucd"
SAMPLE_PATH = OUT_DIR / "sample.csv"
FEWSHOT_PATH = OUT_DIR / "fewshot_examples.json"
FEWSHOT_PER_SITE = 20
FEWSHOT_TAG = "+fewshot"

COLS = ["UniversityID", "WOID", "WODescription", "WOPriority", "PPM/UPM", "SystemDescription",
        "ComponentDescription"]
LABELS = ["LOW", "MEDIUM", "HIGH"]
SEED = 20260918
SAMPLE_PER_BAND = 100
MIN_CHARS, MAX_CHARS = 3, 200


def _chunks(chunksize: int = 500_000):
    return pd.read_csv(CSV_PATH, usecols=COLS, dtype=str, chunksize=chunksize, on_bad_lines="skip")


def unplanned() -> pd.DataFrame:
    """Unplanned work orders with a usable description (no model involved)."""
    keep = []
    for chunk in _chunks():
        c = chunk[chunk["PPM/UPM"].str.upper().fillna("") == "UPM"].copy()
        # Excel export artefacts: "_x000D_" carriage returns and collapsed whitespace. Cleaning is
        # identical for every strategy and does not touch wording.
        c["WODescription"] = (c["WODescription"].fillna("").str.replace("_x000D_", " ", regex=False)
                              .str.replace(r"\s+", " ", regex=True).str.strip())
        c = c[c["WODescription"].str.len().between(MIN_CHARS, MAX_CHARS)]
        keep.append(c)
    df = pd.concat(keep, ignore_index=True)
    df["WOPriority"] = df["WOPriority"].fillna("").str.strip()
    return df[df["WOPriority"] != ""]


# ─────────────────────────────────────────────────────────────────────────────
# inspect
# ─────────────────────────────────────────────────────────────────────────────

def inspect() -> Path:
    df = unplanned()
    rng = np.random.default_rng(SEED)
    md = ["# FMUCD priority-code profile (unplanned work orders)\n",
          "**Generated by:** `python -m research.fmucd inspect`\n",
          "Label metadata only: no strategy has been run on this data. Used to write "
          "`research/external/fmucd_mapping.json` (analysis plan section G, stage 1).\n",
          f"Unplanned work orders with a 3–200 character description: {len(df):,} "
          f"across {df['UniversityID'].nunique()} universities.\n"]
    for uni, g in df.groupby("UniversityID"):
        counts = g["WOPriority"].value_counts()
        md.append(f"\n## University {uni} — {len(g):,} work orders, {len(counts)} priority codes\n")
        md.append("| Priority | Work orders | Share | Example descriptions |")
        md.append("|---|---|---|---|")
        for code, n in counts.head(12).items():
            sub = g[g["WOPriority"] == code]["WODescription"]
            picks = sub.iloc[rng.choice(len(sub), size=min(3, len(sub)), replace=False)].tolist()
            md.append(f"| {code} | {n:,} | {n / len(g):.1%} | " + "; ".join(p.replace("|", "/")[:70] for p in picks) + " |")
        if len(counts) > 12:
            md.append(f"| … {len(counts) - 12} more codes | {counts.iloc[12:].sum():,} | | |")
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUT_DIR / "priority_profile.md"
    path.write_text("\n".join(md) + "\n", encoding="utf-8")
    return path


# ─────────────────────────────────────────────────────────────────────────────
# sample
# ─────────────────────────────────────────────────────────────────────────────

def sample() -> Path:
    from agents.input_guard import is_valid_fault_input

    mapping = json.loads(MAPPING_PATH.read_text(encoding="utf-8"))
    codes = {(u, c): band for u, spec in mapping["universities"].items()
             for band, cs in spec["bands"].items() for c in cs}
    df = unplanned()
    df["band"] = [codes.get((u, c)) for u, c in zip(df["UniversityID"], df["WOPriority"])]
    mapped = df[df["band"].notna()].copy()
    mapped["guard_ok"] = [is_valid_fault_input(t)[0] for t in mapped["WODescription"]]
    guard_rate = float(mapped["guard_ok"].mean())
    pool = mapped[mapped["guard_ok"]].drop_duplicates(subset=["WODescription"])

    rng = np.random.default_rng(SEED)
    picks = []
    for band, g in pool.groupby("band"):
        # spread across universities: round-robin over universities, seeded order within each
        per_uni = {u: sub.iloc[rng.permutation(len(sub))] for u, sub in g.groupby("UniversityID")}
        order, i = [], 0
        while len(order) < min(SAMPLE_PER_BAND, len(g)):
            added = False
            for u, sub in per_uni.items():
                if i < len(sub) and len(order) < min(SAMPLE_PER_BAND, len(g)):
                    order.append(sub.iloc[i])
                    added = True
            if not added:
                break
            i += 1
        picks.append(pd.DataFrame(order))
    out = pd.concat(picks, ignore_index=True)
    out = out.rename(columns={"WOID": "bank_id", "WODescription": "text", "UniversityID": "university"})
    out["design_severity"] = out["band"]
    out["style"] = "workorder"
    out["anchor"] = out["university"]
    out = out[["bank_id", "text", "design_severity", "style", "anchor", "university", "WOPriority",
               "SystemDescription", "ComponentDescription"]]
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out.to_csv(SAMPLE_PATH, index=False)
    meta = {"unplanned_with_description": int(len(df)), "mapped": int(len(mapped)),
            "input_guard_pass_rate": guard_rate, "pool_after_dedup": int(len(pool)),
            "sampled": int(len(out)), "by_band": out["design_severity"].value_counts().to_dict(),
            "by_university": out["university"].value_counts().to_dict(), "seed": SEED}
    (OUT_DIR / "sample_meta.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
    return SAMPLE_PATH


def load_sample(fewshot: bool = False) -> list[dict]:
    """Prompt-bank interface for collect.py. With fewshot=True each prompt carries a system prompt
    that appends labelled examples from its own university (analysis plan section H)."""
    df = pd.read_csv(SAMPLE_PATH)
    prompts = [{"id": r.bank_id, "text": r.text, "design_severity": r.design_severity, "style": r.style,
                "anchor": r.anchor, "machine_id": 1} for r in df.itertuples()]
    if fewshot:
        blocks = fewshot_prompts()
        for prompt, uni in zip(prompts, df["university"].astype(str)):
            prompt["system_prompt"] = blocks[uni]
    return prompts


def build_fewshot_examples() -> Path:
    """20 labelled work orders per university, drawn from the mapped pool outside the sample."""
    mapping = json.loads(MAPPING_PATH.read_text(encoding="utf-8"))
    codes = {(u, c): band for u, spec in mapping["universities"].items()
             for band, cs in spec["bands"].items() for c in cs}
    sample_df = pd.read_csv(SAMPLE_PATH)
    df = unplanned()
    df["band"] = [codes.get((u, c)) for u, c in zip(df["UniversityID"], df["WOPriority"])]
    pool = df[df["band"].notna() & ~df["WODescription"].isin(set(sample_df["text"]))]
    pool = pool.drop_duplicates(subset=["WODescription"])
    rng = np.random.default_rng(SEED)
    out = {}
    for uni, g in pool.groupby("UniversityID"):
        bands = list(g["band"].unique())
        per_band = max(1, FEWSHOT_PER_SITE // len(bands))
        picks = []
        for band, sub in g.groupby("band"):
            take = sub.iloc[rng.permutation(len(sub))[:per_band]]
            picks += [{"text": r.WODescription, "band": band} for r in take.itertuples()]
        rng.shuffle(picks)
        out[str(uni)] = picks[:FEWSHOT_PER_SITE]
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    FEWSHOT_PATH.write_text(json.dumps(out, indent=2), encoding="utf-8")
    print({u: len(v) for u, v in out.items()})
    return FEWSHOT_PATH


def fewshot_prompts() -> dict[str, str]:
    """University id -> production system prompt with that site's labelled examples appended."""
    from agents.prompts import DIAGNOSTIC_SYSTEM_PROMPT

    examples = json.loads(FEWSHOT_PATH.read_text(encoding="utf-8"))
    blocks = {}
    header = ("\n== SEVERITY EXAMPLES FROM THIS SITE (FOLLOW THESE CONVENTIONS) ==\n"
              "Past work orders from the same maintenance organisation, with the severity that "
              "organisation assigned. Use them to calibrate fault_severity for this site.\n")
    for uni, rows in examples.items():
        lines = "\n".join('  "{}" -> {}'.format(r["text"], r["band"]) for r in rows)
        blocks[uni] = DIAGNOSTIC_SYSTEM_PROMPT + header + lines + "\n"
    return blocks


def check_sample(fewshot: bool = False) -> list[str]:
    if not SAMPLE_PATH.exists():
        return ["sample.csv missing: run `python -m research.fmucd sample` first"]
    df = pd.read_csv(SAMPLE_PATH)
    problems = []
    if df["bank_id"].duplicated().any():
        problems.append("duplicate work-order ids")
    if not set(df["design_severity"]) <= set(LABELS):
        problems.append("unexpected band label")
    if fewshot and not FEWSHOT_PATH.exists():
        problems.append("fewshot_examples.json missing: run `python -m research.fmucd fewshot` first")
    return problems


# ─────────────────────────────────────────────────────────────────────────────
# score
# ─────────────────────────────────────────────────────────────────────────────

def non_llm_severities(prompts: list[dict]) -> pd.DataFrame:
    """Rule-based and trained (R1, R3) severities for every sampled work order."""
    from dl_engine.inference import get_healthy_baseline
    from research.baselines import STRATEGIES
    from research.trained_baselines import ARMS as TRAINED_ARMS, EXTERNAL_SUFFIX, classify_external

    rule_based = ["keyword_regex_severity", "keyword_regex_extended", "embedding_severity"]
    base = get_healthy_baseline(noise_std_frac=0.0)
    rows = []
    for arm in rule_based + TRAINED_ARMS:
        for p in prompts:
            rows.append({"arm": arm, "bank_id": p["id"],
                         "severity": STRATEGIES[arm](p["text"], base)[1]["fault_severity"]})
    for arm in TRAINED_ARMS:
        for p in prompts:
            rows.append({"arm": arm + EXTERNAL_SUFFIX, "bank_id": p["id"],
                         "severity": classify_external(arm, p["text"])})
    return pd.DataFrame(rows)


def quadratic_kappa(a: pd.Series, b: pd.Series) -> float:
    idx = {l: i for i, l in enumerate(LABELS)}
    x, y = a.map(idx).to_numpy(), b.map(idx).to_numpy()
    n = len(LABELS)
    w = np.array([[(i - j) ** 2 / (n - 1) ** 2 for j in range(n)] for i in range(n)])
    obs = np.zeros((n, n))
    for i, j in zip(x, y):
        obs[i, j] += 1
    obs /= obs.sum()
    exp = np.outer(np.bincount(x, minlength=n) / len(x), np.bincount(y, minlength=n) / len(y))
    denom = (w * exp).sum()
    return float(1 - (w * obs).sum() / denom) if denom > 0 else float("nan")


def score() -> Path:
    from research.paraphrase.collect import ARMS, load_outputs
    from research.replay_utils import bootstrap_ci, holm_adjust, paired_difference
    from research.trained_baselines import EXTERNAL_SUFFIX, REFERENCE_ARM

    prompts = load_sample()
    meta = pd.DataFrame(prompts).rename(columns={"id": "bank_id", "design_severity": "label"})
    cols = ["arm", "bank_id", "repeat", "severity", "fallback", "latency_ms"]
    llm = load_outputs("fmucd")[cols]
    llm = llm[llm["arm"].isin(ARMS)]
    if (OUT_DIR.parent / "paraphrase").exists():
        try:                                   # few-shot arms: same models, this site's labels in the prompt
            few = load_outputs("fmucd_fewshot")[cols]
            few = few[few["arm"].isin(ARMS)].assign(arm=lambda d: d["arm"] + FEWSHOT_TAG)
            llm = pd.concat([llm, few], ignore_index=True)
        except FileNotFoundError:
            pass
    non_llm = non_llm_severities(prompts)
    non_llm["repeat"] = 0
    non_llm["fallback"] = False
    df = pd.concat([llm, non_llm], ignore_index=True).merge(meta[["bank_id", "label", "anchor"]], on="bank_id")
    df["correct"] = (df["severity"] == df["label"]).astype(float)

    rows = []
    for arm, g in df.groupby("arm"):
        lo, hi = bootstrap_ci(g["correct"], g["anchor"])
        rows.append({"arm": arm, "n": len(g), "agreement": float(g["correct"].mean()), "ci_lo": lo, "ci_hi": hi,
                     "kappa": quadratic_kappa(g["severity"], g["label"]),
                     "share_high": float((g["severity"] == "HIGH").mean()),
                     "share_low": float((g["severity"] == "LOW").mean()),
                     "fallback_rate": float(g["fallback"].astype(bool).mean())})
    agreement = pd.DataFrame(rows).sort_values("agreement", ascending=False).set_index("arm")

    references = ["keyword_regex_severity", REFERENCE_ARM, REFERENCE_ARM + EXTERNAL_SUFFIX]
    llm_arms = sorted(a for a in df["arm"].unique() if a.endswith("__production"))
    paired = []
    for ref in references:
        for arm in llm_arms:
            m = df[df["arm"] == arm][["bank_id", "anchor", "correct"]].merge(
                df[df["arm"] == ref][["bank_id", "correct"]], on="bank_id", suffixes=("_arm", "_ref"))
            res = paired_difference(m["correct_arm"], m["correct_ref"], m["anchor"], seed=SEED)
            paired.append({"reference": ref, "arm": arm, "arm_agreement": float(m["correct_arm"].mean()),
                           "reference_agreement": float(m["correct_ref"].mean()), **res})
    paired = pd.DataFrame(paired)
    paired["p_holm"] = holm_adjust(paired["p"].tolist())

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    agreement.to_csv(OUT_DIR / "agreement.csv")
    paired.to_csv(OUT_DIR / "paired.csv", index=False)
    df.to_csv(OUT_DIR / "rows.csv.gz", index=False, compression="gzip")

    sample_meta = json.loads((OUT_DIR / "sample_meta.json").read_text(encoding="utf-8"))
    mapping = json.loads(MAPPING_PATH.read_text(encoding="utf-8"))
    md = ["# External check — FMUCD work orders\n", "**Generated by:** `python -m research.fmucd score`\n",
          "Agreement between each strategy's severity and the band the organisation's own priority code maps to "
          "(`research/external/fmucd_mapping.json`, frozen before sampling). Recorded priority encodes scheduling "
          "policy as much as severity, so this is an agreement study, not an accuracy test.\n",
          f"Sample: {sample_meta['sampled']} unplanned work orders "
          f"({', '.join(f'{k} {v}' for k, v in sample_meta['by_band'].items())}) from "
          f"{len(sample_meta['by_university'])} universities; input guard passed "
          f"{sample_meta['input_guard_pass_rate']:.1%} of mapped work orders.\n",
          "Mapping rationale per university: " + "; ".join(
              f"{u}: {spec['rationale']}" for u, spec in mapping["universities"].items()) + "\n",
          "\n## 1. Agreement with the recorded priority band\n",
          "| Arm | Agreement [95% CI] | Quadratic kappa | Share HIGH | Share LOW | Fallback |", "|---|---|---|---|---|---|"]
    for arm, r in agreement.iterrows():
        md.append(f"| {arm} | {r['agreement']:.1%} [{r['ci_lo']:.0%}, {r['ci_hi']:.0%}] | {r['kappa']:.2f} | "
                  f"{r['share_high']:.0%} | {r['share_low']:.0%} | {r['fallback_rate']:.0%} |")
    md.append("\nCIs resample universities. `*" + EXTERNAL_SUFFIX + "` are the trained classifiers refitted on the "
              "prompt vocabulary plus every labelled prompt of our own banks (regime R3): labelled reports from a "
              "different site.\n")
    md.append("\n## 2. Production-prompt LLMs minus each reference\n")
    md.append("Percentage points, 95% cluster-bootstrap CI (universities), sign-flip p, Holm across the "
              f"{len(paired)} comparisons.\n")
    md.append("| Reference | Arm | Arm | Reference | Difference [95% CI] | p (Holm) |")
    md.append("|---|---|---|---|---|---|")
    for r in paired.itertuples():
        md.append(f"| {r.reference} | {r.arm} | {r.arm_agreement:.1%} | {r.reference_agreement:.1%} | "
                  f"{r.diff * 100:+.1f} [{r.ci_lo * 100:+.0f}, {r.ci_hi * 100:+.0f}] | {r.p_holm:.4f} |")
    fewshot_arms = sorted(a for a in df["arm"].unique() if a.endswith(FEWSHOT_TAG))
    if fewshot_arms:
        n_ex = {u: len(v) for u, v in json.loads(FEWSHOT_PATH.read_text(encoding="utf-8")).items()}
        md.append("\n## 2b. Few-shot: the same models with this site's own labelled examples in the prompt\n")
        md.append(f"Each work order is judged with {min(n_ex.values())}–{max(n_ex.values())} labelled work orders from "
                  "its own university appended to the production system prompt (analysis plan section H; examples "
                  "drawn outside the evaluated sample). Difference = few-shot − zero-shot on the same work orders, "
                  "95% cluster-bootstrap CI over universities, unadjusted sign-flip p.\n")
        md.append("Difference and CI are over the 300 work orders (resampling universities); the sign-flip p is over "
                  "the four university means, so it cannot go below 0.125.\n")
        md.append("| Arm | Zero-shot | Few-shot | Difference [95% CI] | p |")
        md.append("|---|---|---|---|---|")
        fs_rows = []
        for arm in fewshot_arms:
            base = arm[: -len(FEWSHOT_TAG)]
            m = df[df["arm"] == arm][["bank_id", "anchor", "correct"]].merge(
                df[df["arm"] == base][["bank_id", "correct"]], on="bank_id", suffixes=("_few", "_zero"))
            gain = m["correct_few"] - m["correct_zero"]
            lo, hi = bootstrap_ci(gain, m["anchor"])
            res = paired_difference(m["correct_few"], m["correct_zero"], m["anchor"], seed=SEED)
            fs_rows.append({"arm": base, "zero_shot": float(m["correct_zero"].mean()),
                            "few_shot": float(m["correct_few"].mean()), "diff": float(gain.mean()),
                            "ci_lo": lo, "ci_hi": hi, "p": res["p"],
                            "diff_university_mean": res["diff"]})
            md.append(f"| {base} | {m['correct_zero'].mean():.1%} | {m['correct_few'].mean():.1%} | "
                      f"{gain.mean() * 100:+.1f} [{lo * 100:+.0f}, {hi * 100:+.0f}] | {res['p']:.3f} |")
        pd.DataFrame(fs_rows).to_csv(OUT_DIR / "fewshot.csv", index=False)

    oracle_path = OUT_DIR / "oracle.csv"
    if oracle_path.exists():
        orc = pd.read_csv(oracle_path)
        md.append("\n## 3. Upper bound: classifiers trained on this data's own labels\n")
        md.append("Trained on mapped work orders disjoint from the sample (same universities and filters), tested on "
                  "the same 300. Shows how much of the recorded band is predictable from the text at all.\n")
        md.append("| Model | Training work orders | Agreement | Quadratic kappa |")
        md.append("|---|---|---|---|")
        for r in orc.itertuples():
            md.append(f"| {r.model} | {r.n_train:,} | {r.agreement:.1%} | {r.kappa:.2f} |")
        md.append("\nThe gap between this and every arm in section 1 is the finding: the priority band is learnable "
                  "from the text, but it encodes each site's own conventions, which neither a general language model "
                  "nor a classifier trained elsewhere can infer.\n")
    md.append("\n## 4. Confusion with the recorded band (selected arms)\n")
    for arm in [a for a in ("gemini_2_5_flash_nothink__production", "qwen3_8_27b__production",
                            REFERENCE_ARM, REFERENCE_ARM + EXTERNAL_SUFFIX, "keyword_regex_severity")
                if a in set(df["arm"])]:
        g = df[df["arm"] == arm]
        tab = pd.crosstab(g["label"], g["severity"]).reindex(index=LABELS, columns=LABELS, fill_value=0)
        md.append(f"\n**{arm}** (rows: recorded band, columns: predicted)\n")
        md.append("| | " + " | ".join(LABELS) + " |")
        md.append("|---|" + "---|" * len(LABELS))
        for lab in LABELS:
            md.append(f"| {lab} | " + " | ".join(str(int(tab.loc[lab, c])) for c in LABELS) + " |")
    path = OUT_DIR / "summary.md"
    path.write_text("\n".join(md) + "\n", encoding="utf-8")
    return path


def oracle(n_train: int = 6000) -> Path:
    """How much of the recorded band is predictable from the text by a model trained on this data?

    Trains on mapped work orders disjoint from the evaluated sample (same universities, same filters)
    and tests on the sample. This is an upper bound for any text-only method on these labels.
    """
    from sklearn.linear_model import LogisticRegression
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.pipeline import make_union
    from research.trained_baselines import encode

    mapping = json.loads(MAPPING_PATH.read_text(encoding="utf-8"))
    codes = {(u, c): band for u, spec in mapping["universities"].items()
             for band, cs in spec["bands"].items() for c in cs}
    sample_df = pd.read_csv(SAMPLE_PATH)
    df = unplanned()
    df["band"] = [codes.get((u, c)) for u, c in zip(df["UniversityID"], df["WOPriority"])]
    pool = df[df["band"].notna() & ~df["WODescription"].isin(set(sample_df["text"]))]
    pool = pool.drop_duplicates(subset=["WODescription"])
    rng = np.random.default_rng(SEED)
    train = pd.concat([g.iloc[rng.permutation(len(g))[:n_train // 3]] for _, g in pool.groupby("band")])

    rows = []
    for name in ("tfidf_logreg", "bge_m3_logreg"):
        if name == "tfidf_logreg":
            vec = make_union(TfidfVectorizer(analyzer="word", ngram_range=(1, 2), sublinear_tf=True),
                             TfidfVectorizer(analyzer="char_wb", ngram_range=(2, 5), sublinear_tf=True))
            X, Xt = vec.fit_transform(train["WODescription"]), vec.transform(sample_df["text"])
        else:
            X = encode("bge_m3", train["WODescription"].tolist())
            Xt = encode("bge_m3", sample_df["text"].tolist())
        clf = LogisticRegression(C=1.0, class_weight="balanced", max_iter=5000).fit(X, train["band"])
        pred = clf.predict(Xt)
        rows.append({"model": name + "_fmucd_trained", "n_train": len(train),
                     "agreement": float(np.mean(pred == sample_df["design_severity"].to_numpy())),
                     "kappa": quadratic_kappa(pd.Series(pred), sample_df["design_severity"])})
    out = pd.DataFrame(rows)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out.to_csv(OUT_DIR / "oracle.csv", index=False)
    print(out.to_string(index=False))
    return OUT_DIR / "oracle.csv"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("step", choices=["inspect", "sample", "fewshot", "oracle", "score"])
    args = parser.parse_args()
    path = {"inspect": inspect, "sample": sample, "fewshot": build_fewshot_examples,
            "oracle": oracle, "score": score}[args.step]()
    print(f"[fmucd] wrote {path.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
